### PR TITLE
Fix: "RuntimeError: The 'data' object was created by an older version of PyG"?

### PR DESCRIPTION
**Pull request by warpmatrix**
I met the same issue as https://github.com/jianhao2016/GPRGNN/issues/11#issue-1074005931.
I wonder if it's useful to fix this issue by using the new api of pyg instead of the code in dataset_utils.py? Since I'm a newcomer, I don't know whether the new dataset downloaded from pyg is equivalent to your dataset.

I ran the dataset of chameleon, squirrel and film and my environment is:

- numpy==1.20.2
- torch==1.9.0+cu111
- torch_geometric==2.0.3
- torch_sparse==0.6.12
- tqdm==4.62.3

### CODE REVIEW

**Comment by elichienxD** [comment]
Hi @warpmatrix 

Thanks for your contribution! Ideally, the dataset provided by PyG is identical to those used in our repo. Still, I'll double check it with your code in a few days. After that, I'll merge your pull request.  

Eli

**Comment by elichienxD** [comment]
Hi @warpmatrix ,

I've checked the code and it seems okay. The only problem is that when loading dataset "chameleon" and "squirrel", we use the original graph instead of the geom-gcn preprocessed one. Thus, in your modification, instead of

dataset = WikipediaNetwork(
            root='../data/', name=name, transform=T.NormalizeFeatures())

It should be

dataset = WikipediaNetwork(
            root='../data/', name=name,geom_gcn_preprocess=False, transform=T.NormalizeFeatures())

in order to get the right graph. Unfortunately, this will in return the raw node labels (dataset[0].y). So a quick fix now is to use everything from "geom_gcn_preprocess=False" and only the node label y from "geom_gcn_preprocess=True". Would you mind to modify your code? After that I'll merge your pull request.

Thanks,
Eli

**Comment by warpmatrix** [comment]
Hi @elichienxD ,

Thank you for your replay. I tried to modify the code as you mentioned above to use everything from "geom_gcn_preprocess=False" and only the node label y from "geom_gcn_preprocess=True". However, it seems `dataset[0].y` is an immutable object, since I printed the data of `dataset[0].y` before and after assignment. And there is no different between them. I'm willing to offer help but I got stuck. Maybe you can directly edit the code on my master branch.

```diff
--- a/src/dataset_utils.py
+++ b/src/dataset_utils.py
@@ -210,8 +210,16 @@ def DataLoader(name):
         path = osp.join(root_path, 'data', name)
         dataset = Amazon(path, name, T.NormalizeFeatures())
     elif name in ['chameleon', 'squirrel']:
+        # use everything from "geom_gcn_preprocess=False" and
+        # only the node label y from "geom_gcn_preprocess=True"
         dataset = WikipediaNetwork(
-            root='../data/', name=name, transform=T.NormalizeFeatures())
+            root='../data/', name=name, geom_gcn_preprocess=False, transform=T.NormalizeFeatures())
+        preProcDs = WikipediaNetwork(
+            root='../data/', name=name, geom_gcn_preprocess=True, transform=T.NormalizeFeatures())
+        print("before assignment:", dataset[0].y, preProcDs[0].y)
+        dataset[0].y = preProcDs[0].y
+        # dataset[0].y.copy_(preProcDs[0].y)
+        print("after assignment:", dataset[0].y, preProcDs[0].y)
     elif name in ['film']:
         dataset = Actor(
             root='../data/film', transform=T.NormalizeFeatures())
```

```
before assignment: tensor([ 8.2385, 10.3735,  7.1499,  ...,  6.6871,  7.5501,  7.7981]) tensor([1, 3, 0,  ..., 0, 1, 1])
after assignment: tensor([ 8.2385, 10.3735,  7.1499,  ...,  6.6871,  7.5501,  7.7981]) tensor([1, 3, 0,  ..., 0, 1, 1])
```

Thanks,
warpmatrix

**Comment by warpmatrix** [comment]
Hi @elichienxD ,

I changed the return values of `DataLoader` function to fix the problem mentioned above hoping you don't mind that. Now the code can run without problem and you can double check it again.

Thanks for your work,
warpmatrix

**Comment by elichienxD** [comment]
Hi @warpmatrix ,

Thanks again for your contribution. I've merged your pull request. Also, I slightly change your code (basically set dataset = "geom_gcn=False" and then copy edge_index from "geom_gcn=True" to it). This is because we will call `dataset.num_classes` later so the node label in dataset must be correct (also, the node features are the same).

Additionally, I add `Reproduce_GPRGNN.sh` to easily reproduce our results in Table 2 for GPRGNN.

Best,
Eli

**Pull request merged**
